server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kosta.bus_reserve2.domain


spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: bus1234
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp